spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookreader?useUnicode=true&characterEncoding=utf8
    username: root
    password: zhengyuyan
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/